package io.terminus.doctor.basic.service;

import com.google.common.base.Throwables;
import io.terminus.boot.rpc.common.annotation.RpcProvider;
import io.terminus.common.model.PageInfo;
import io.terminus.common.model.Paging;
import io.terminus.common.model.Response;
import io.terminus.doctor.basic.dao.PhoenixCoderDao;
import io.terminus.doctor.basic.model.PhoenixCoder;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Map;

/**
 * Code generated by CodeGen
 * Desc: 程序员表读服务实现类
 * Date: 2016-11-23
 */
@Slf4j
@Service
@RpcProvider
public class PhoenixCoderReadServiceImpl implements PhoenixCoderReadService {

    private final PhoenixCoderDao phoenixCoderDao;

    @Autowired
    public PhoenixCoderReadServiceImpl(PhoenixCoderDao phoenixCoderDao) {
        this.phoenixCoderDao = phoenixCoderDao;
    }

    @Override
    public Response<PhoenixCoder> findCoderById(Long coderId) {
        try {
            return Response.ok(phoenixCoderDao.findById(coderId));
        } catch (Exception e) {
            log.error("find coder by id failed, coderId:{}, cause:{}", coderId, Throwables.getStackTraceAsString(e));
            return Response.fail("coder.find.fail");
        }
    }

    @Override
    public Response<List<PhoenixCoder>> findAllCoders() {
        try {
            return Response.ok(phoenixCoderDao.listAll());
        } catch (Exception e) {
            log.error("find all coder failed, cause:{}", Throwables.getStackTraceAsString(e));
            return Response.fail("coder.find.fail");
        }
    }

    @Override
    public Response<Paging<PhoenixCoder>> pagingCoder(Map<String, Object> criteria, Integer pageNo, Integer size) {
        try {
            PageInfo page = PageInfo.of(pageNo, size);
            return Response.ok(phoenixCoderDao.paging(page.getOffset(), page.getLimit(), criteria));
        } catch (Exception e) {
            log.error("paging coder failed, criteria:{}, pageNo:{}, size:{}, cause:{}", criteria, pageNo, size, Throwables.getStackTraceAsString(e));
            return Response.fail("coder.find.fail");
        }
    }
}
