package io.terminus.doctor.basic.model;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * Code generated by CodeGen
 * Desc: 程序员表Model类
 * Date: 2016-11-23
 */
@Data
public class PhoenixCoder implements Serializable {
    //TODO: Do not forget add "serialVersionUID" field!

    private Long id;
    
    /**
     * 姓名
     */
    private String name;
    
    /**
     * 手机号
     */
    private String mobile;
    
    /**
     * 程序员类型
     */
    private Integer type;
    
    /**
     * 创建时间
     */
    private Date createdAt;
    
    /**
     * 修改时间
     */
    private Date updatedAt;
}
