package io.terminus.doctor.basic.service;

import io.terminus.common.model.Paging;
import io.terminus.common.model.Response;
import io.terminus.doctor.basic.model.PhoenixCoder;

import javax.validation.constraints.NotNull;
import java.util.List;
import java.util.Map;

/**
 * Code generated by CodeGen
 * Desc: 程序员表读服务
 * Date: 2016-11-23
 */
public interface PhoenixCoderReadService {

    /**
     * 根据id查询程序员表
     * @param coderId 主键id
     * @return 程序员表
     */
    Response<PhoenixCoder> findCoderById(@NotNull(message = "coderId.not.null") Long coderId);

    /**
     * 查询所有程序员表
     * @return 所有程序员表
     */
    Response<List<PhoenixCoder>> findAllCoders();

    /**
     * 分页查询程序员表
     * @param criteria  查询条件
     * @param pageNo    当前页码
     * @param size      分页大小
     * @return 程序员表分页查询结果
     */
    Response<Paging<PhoenixCoder>> pagingCoder(Map<String, Object> criteria, Integer pageNo, Integer size);
}
