packageio.terminus.doctor.basic.dao;

import io.terminus.common.mysql.dao.MyBatisDao;
import io.terminus.doctor.basic.model.PhoenixCoder;
import org.springframework.stereotype.Repository;

/**
 * Code generated by CodeGen
 * Desc: 程序员表Dao类
 * Date: 2016-11-23
 */
@Repository
public class PhoenixCoderDao extends MyBatisDao<PhoenixCoder> {

}
