package io.terminus.doctor.basic.service;

import io.terminus.common.model.Response;
import io.terminus.doctor.basic.model.PhoenixCoder;

import javax.validation.constraints.NotNull;

/**
 * Code generated by CodeGen
 * Desc: 程序员表写服务
 * Date: 2016-11-23
 */
public interface PhoenixCoderWriteService {

    /**
     * 创建PhoenixCoder
     * @param coder
     * @return 主键id
     */
    Response<Long> createCoder(PhoenixCoder coder);

    /**
     * 更新PhoenixCoder
     * @param coder
     * @return 是否成功
     */
    Response<Boolean> updateCoder(PhoenixCoder coder);

    /**
     * 根据主键id删除PhoenixCoder
     * @param coderId
     * @return 是否成功
     */
    Response<Boolean> deleteCoderById(@NotNull(message = "coderId.not.null") Long coderId);
}